oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java, oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
This change is dependent on the previous pull request, so only the 2nd commit needs separate review. When the first change is in I'll revise this. 
@ejona86 @tbetbetbe can you review?
=> Add ServiceAccountJwtHeaderCredentials

oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java, oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
When this API is called from GAE, the file system checks will throw a security exception. These should be treated as if the files did not exists to enable the other types of credentials to work.
=> Fix security exceptions running Default Credentials in GAE sandbox.

oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java, oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java, oauth2_http/java/com/google/auth/oauth2/UserCredentials.java, oauth2_http/javatests/com/google/auth/http/HttpCredentialsAdapterTest.java, oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java, oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
3-legged-auth has access token with optional refresh token. Breaking change to UserCredentials constructors.
=> Add AccessToken to UserCredentials constructors.

oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java, oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java, oauth2_http/java/com/google/auth/oauth2/UserCredentials.java, oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java, oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java, oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
For UserCredentials and ServiceAccountCredentials.
Breaking change to long form constructors of UserCredentials and ServiceAccountCredentials.
=> Standardize URI type for custom token server

appengine/pom.xml, credentials/pom.xml, oauth2_http/pom.xml, pom.xml
This reverts commit 9dc09c66f9edb936340c343fd0730b89dc3c9344.
=> Change version back to 0.4.0-SNAPSHOT

oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
I'm not quite sure why getRefreshToken was made final. Made all final for consistency. Please let me know if you want to drop the modifier.
=> add accessor methods to UserCredentials

appengine/pom.xml, credentials/pom.xml, oauth2_http/pom.xml, pom.xml
Update version to 0.4.0
@ejona86 FYI
@sduskis FYI
=> Prepare for Release

credentials/java/com/google/auth/Credentials.java, credentials/java/com/google/auth/RequestMetadataCallback.java
Resolves #3
@louiscryan @ejona86
=> Add asynchronous getRequestMetadata.

oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java, oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java, oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java, oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java, oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
=> Remove OAuth2Utils.exceptionWithCause, use exception costructor instead

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This PR adds missing README and related CONTRIBUTING and CODE_OF_CONDUCT files.
This should be merged only once version 0.5.0 is out and #76 is merged.
=> Add README.md, CONTRIBUTING.md and CODE_OF_CONDUCT.md

README.md
=> Update README to point to version 0.6.0

oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
Change refresh time to start 5 minutes before expiration from 1 minute. 
b/36219599
=> Refresh token w/ 5 min left

appengine/pom.xml
Add provided to the pom for the GAE SDK
=> missed commit

oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java, oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java, oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
As the title goes, there are a few unnecessary imports and suppress warnings annotations.
=> Minor cleanup removing unnecessary imports and suppress warnings

oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
=> Fixes comment typos.

README.md, RELEASE.md, appengine/pom.xml, credentials/pom.xml, oauth2_http/pom.xml, pom.xml
https://repo1.maven.org/maven2/com/google/auth/google-auth-library-parent/0.9.1/
/cc @igorbernstein2
=> bump release from 0.9.1-SNAPSHOT to 0.9.1

README.md, scripts/update_javadoc.sh
Fixes #113
Will have to run this manually after this is merged to have latest show the current 0.9.1 docs.
=> Versionless docs

oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
=> Add documentation note that getAccessToken() returns cached value

oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java, oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
=> Log warning if default credentials yields a user token from gcloud sdk

oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
=> Update new token urls

appengine/java/com/google/auth/appengine/AppEngineCredentials.java, credentials/java/com/google/auth/Credentials.java, credentials/java/com/google/auth/RequestMetadataCallback.java, credentials/java/com/google/auth/ServiceAccountSigner.java, oauth2_http/java/com/google/auth/http/HttpTransportFactory.java, oauth2_http/java/com/google/auth/oauth2/AccessToken.java, oauth2_http/java/com/google/auth/oauth2/ClientId.java, oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java, oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java, oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java, oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java, oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java, oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java, oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
Fixes javadoc warnings and lowers the log level of the ComputeEngine detection to INFO.
Fixes #198
=> Fix warnings

README.md
=> Docs: How to install App Engine SDK and run tests

pom.xml
=> Update google-http-java-client dependency version

appengine/pom.xml, credentials/pom.xml, oauth2_http/pom.xml, pom.xml, versions.txt
=> Bump next snapshot

.kokoro/release/publish_javadoc.cfg, .kokoro/release/publish_javadoc.sh
This will move us closer to autorelease.
=> Add kokoro job for publishing javadoc to GCS

oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
=> Use OutputStream directly instead of PrintWriter

.kokoro/release/drop.sh, .kokoro/release/promote.sh
Allow Kokoro jobs to drop or promote the release.
=> Provide STAGING_REPOSITORY_ID as an environment variable

.kokoro/release/stage.cfg
autorelease requires more credentials
=> Add credentials for autorelease

README.md
Clarifying some information from #272
=> Update instructions for google-auth-library-appengine artifact

.kokoro/continuous/dependencies.cfg, .kokoro/continuous/java10.cfg, .kokoro/continuous/java9.cfg, .kokoro/dependencies.sh, .kokoro/presubmit/dependencies.cfg, .kokoro/presubmit/java10.cfg, .kokoro/presubmit/java9.cfg, appengine/pom.xml
Ensures that we do not declare any extra dependencies and are declaring all direct dependencies.
=> Adds CI test for mvn dependency:analyze and fixes missing deps

pom.xml
=> Upgrade Guava to 28.0

java.header
=> Update copyright format

.kokoro/release/snapshot.cfg, .kokoro/release/snapshot.sh, bom/pom.xml, pom.xml
* Configures snapshot repository for Sonatype
* Creates Kokoro config and script for publishing the snapshot build
Fixes #294
=> chore: enable nightly snapshot release

.kokoro/continuous/propose_release.sh
run in debug mode so that we can get a bit more insight into why the task is failing.
=> build: run in debug mode

pom.xml
=> Remove obsolete parent POM

oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
=> fix: make JwtClaims.newBuilder() public

pom.xml
=> Update Guava to 28.1

pom.xml
=> Update appengine API

bom/README.md
=> fix: xml syntax error in bom/README.md

.kokoro/build.sh, .kokoro/dependencies.sh, .kokoro/presubmit/clirr.cfg, pom.xml
This plugin checks for breaking API surface changes
=> build: add clirr check

pom.xml
=> deps: update guava to 28.2-android

.kokoro/linkage-monitor.sh, .kokoro/presubmit/linkage-monitor.cfg
@chingor13 @kolea2 
cl/292391265 has been submitted. Would you trigger the Kokoro job?
=> ci: linkage monitor Kokoro build config for google-auth-library-java

renovate.json
=> deps: pick android version of Guava

pom.xml
=> deps: update Guava to 29.0-android

pom.xml
Try the configuration from google-cloud-shared-config
=> chore: enable profile for AutoValue

appengine/java/com/google/auth/appengine/AppEngineCredentials.java
=> fix: remove bad javadoc tags

LICENSE, synth.py
@chingor13 This was incorrectly changed a month ago.
=> revert to BSD license

oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java, oauth2_http/javatests/com/google/auth/http/HttpCredentialsAdapterTest.java, oauth2_http/pom.xml
=> feat: added getter for credentials object in HttpCredentialsAdapter

.github/release-please.yml, .github/sync-repo-settings.yaml
=> build: configure branch 0.25.2-sp as a release branch

appengine/pom.xml, bom/pom.xml, credentials/pom.xml, oauth2_http/pom.xml, pom.xml
=> build: switch all clients to use the google endpoint on sonatype

oauth2_http/javatests/com/google/auth/oauth2/ITDownscopingTest.java, oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java, oauth2_http/javatests/com/google/auth/oauth2/JwtClaimsTest.java, oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
=> chore: migrate tests in oauth2_http module from JUnit4 to JUnit5 -  fourth iteration (#756)

oauth2_http/javatests/com/google/auth/oauth2/MockExecutor.java, oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java, oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java, oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java, oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsWithRefreshTest.java, oauth2_http/javatests/com/google/auth/oauth2/OAuthExceptionTest.java, oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
=> chore: migrate tests in oauth2_http module from JUnit4 to JUnit5 -  fifth iteration (#756)

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 1.3.0

bom/README.md
=> chore: update branch name in README.md

oauth2_http/java/com/google/auth/oauth2/ExecutableResponse.java, oauth2_http/java/com/google/auth/oauth2/PluggableAuthCredentials.java, oauth2_http/java/com/google/auth/oauth2/PluggableAuthHandler.java, oauth2_http/javatests/com/google/auth/oauth2/ExecutableResponseTest.java, oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthHandlerTest.java, oauth2_http/pom.xml
This PR adds handling for 3rd party executables in the response format outlined in go/pluggable-auth-design.
=> feat: finalizes PluggableAuth implementation

oauth2_http/java/com/google/auth/oauth2/IdToken.java, oauth2_http/javatests/com/google/auth/oauth2/IdTokenTest.java
Adds a test for a reported condition where 0x20 character causes an exception
=> fix: Add Test to validate 0x20 in token

oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java, oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Adding validation for psc endpoints:
sts-*.p.googleapis.com
iamcredentials-*.p.googleapis.com
=> feat: Adding validation for psc endpoints

oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java, oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
Fork of https://github.com/googleapis/google-auth-library-java/pull/1002 with test fixes.
=> fix: Resolve race condition reported in #692

oauth2_http/java/com/google/auth/oauth2/DefaultPKCEProvider.java, oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
=> fix: Java doc for DefaultPKCEProvider.java

.github/release-please.yml, .github/sync-repo-settings.yaml
=> churn: backfilling a branch for LTS 3.0

.kokoro/build.sh, .kokoro/presubmit/graalvm-native-a.cfg, .kokoro/presubmit/graalvm-native-b.cfg, renovate.json
=> chore: make kokoro cfgs version agnostic

oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java, oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Reverts googleapis/google-auth-library-java#1359
=> Revert "Revert "fix: Issue #1347: ExternalAccountCredentials serialization is broken""

README.md
Fixes incorrect format for workload identity pool audience.
=> docs: fix readme documentation for workload custom suppliers.

renovate.json
=> chore: add dependency dashboard to renovate config

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: setup 1.23.x lts branch.

oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
=> chore: fix string format in mock

appengine/pom.xml, bom/pom.xml, credentials/pom.xml, oauth2_http/pom.xml, pom.xml
=> fix: remove unnecessary nexus-staging-maven-plugin activation

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 1.34.0

.kokoro/build.sh, .kokoro/presubmit/graalvm-native-a.cfg, .kokoro/presubmit/graalvm-native-c.cfg
To be merged after cl/747623808
[context doc](https://docs.google.com/document/d/1bOeGtVFLsq5ts71If5pFXCvHIeNpbtBRvF6XQfavLZs/edit?tab=t.dcjxhf429j6t)
TL;DR: we are introducing testing infra for GraalVM for JDK 17
=> build: introduce testing infra for GraalVM "C"

README.md
context: [doc](https://docs.google.com/document/d/1g8HJCstkEEZZc73gFlQO8uPGs07SkWKkr7NG-Yg4bvM/edit?tab=t.0#heading=h.9t58aw3up7to)
=> chore: add link to guide on enable debug logging

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: create LTS branch 1.36.x

.github/workflows/ci.yaml
=> ci: upgrade tests to JDK 25
