googleapis/google-auth-library-java

- credentials/java/com/google/auth/Credentials.java
- oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
A revised version of request #11 that is non-breaking for callers, which should make the staging easier.
> Add URI parameter to getRequestMeatadata.

- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
- appengine/javatests/com/google/auth/appengine/MockAppIdentityService.java
- appengine/pom.xml
- pom.xml
Initial implementation of AppEngineCredentials in new module because of GAE SDK dependencies.
> Google App Engine Credentials.

- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
Moving maven-gpg-plugin into a profile, which is triggered with the performRelease attribute, so that it isn't triggered during a normal "mvn install" command.
> fixing install for users without gpg keys

- oauth2_http/java/com/google/auth/http/AuthHttpConstants.java
- oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java
- oauth2_http/java/com/google/auth/http/InternalAuthHttpConstants.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/TestUtils.java
- oauth2_http/javatests/com/google/auth/http/HttpCredentialsAdapterTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenCheckingTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
Some additional stuff:
* Creating some constants so that hardcoded values aren't repeated
* Fixing a couple spelling errors
* Having MockTokenServerTransport extend HttpTransport directly, since it doesn't use anything from MockHttpTransport
> Fixing https://github.com/google/google-auth-library-java/issues/22

- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
Enables direct use of temporary access tokens by making OAuth2Credentials non-abstract.
> Enable temporary access token scenario

- pom.xml
The old version, 1.6.3, throws ArrayIndexOutOfBounds under Java 8 when
executing "vn nexus-staging:release -DperformRelease=true".
Newer versions fixes this problem. See:
https://issues.sonatype.org/browse/NEXUS-6836 .
> Bump nexus-staging-maven-plugin to 1.6.5

- oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
The Json for shell credentials returns a double for the last item in the list.  I kept on getting the following exception before this change:
2015-12-16 11:29:45,550 INFO  [BigtableSession-startup-0] grpc.BigtableSession: gRPC is using the JDK provider (alpn-boot jar)
2015-12-16 11:29:52,543 INFO  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
2015-12-16 11:29:53,798 WARN  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Got an unexpected exception while trying to refresh google credentials.
java.lang.IllegalArgumentException:
at com.google.bigtable.repackaged.com.google.api.client.json.JsonParser.parseValue(JsonParser.java:871)
at …
> Using Objects for the List type in CloudShellCredentials.

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
We are deprecating the use of the X-Google-Metadata-Request header in favor
of the latest header, Metadata-Flavor.
The transition is explained here:
https://cloud.google.com/compute/docs/metadata#transitioning
> Deprecate X-Google-Metadata-Request in favor new Metadata-Flavor header

- credentials/java/com/google/auth/Credentials.java
I am working on populating our internal (prod) authentication object onto wire in gRPC.  I am going to use `Credentials`, and because the authentication object is serialized as binary headers, I will base64-encode them.
The `Credentials` object will be passed to gRPC `ClientAuthInterceptor` and populated to gRPC `Metadata`, which accepts binary value (`byte[]`) when the key ends with `"-bin"`, and string value otherwise.  Therefore, `ClientAuthInterceptor` needs to decode the base64-encoded binary headers returned by `Crendentials`, and pass through the others.
`ClientAuthInterceptor` could use `"-bin"` as the indicator. However, because it consumes any `Crendentials` implementation, it's not safe for it to rely on this indicator unless it's defined on the `Credentials` interface.
This is …
> Standardize the naming convention of base64-encoded binary data.

- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
- appengine/javatests/com/google/auth/appengine/MockAppIdentityService.java
The expiration information is passed in by the AppIdentityService. Pass along the expiration time for the App Engine Flexible Environment.  Not having this causes problems such as https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/750 and https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/issues/145.
> Adding expiration date to AppEngineCredentials.

- .gitignore
- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
Make DefaultCredentialsProvider respect the CLOUDSDK_CONFIG environment
variable.
> respect the CLOUDSDK_CONFIG

- credentials/java/com/google/auth/Credentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockExecutor.java
- oauth2_http/javatests/com/google/auth/oauth2/MockRequestMetadataCallback.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
The OAuth2 creds will call the callback in network thread if cache is used. Otherwise, will do the blocking IO in the provided executor.
The JWT creds always calls the callback in network thread because it's only local CPU work.
> Implement the async method in oauth2 creds and JWT creds.

- credentials/java/com/google/auth/Credentials.java
- credentials/java/com/google/auth/RequestMetadataCallback.java
- java.header
- license-checks.xml
- oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java
- oauth2_http/java/com/google/auth/http/InternalAuthHttpConstants.java
- oauth2_http/java/com/google/auth/oauth2/AccessToken.java
- oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/TestClock.java
- oauth2_http/javatests/com/google/auth/TestUtils.java
- oauth2_http/javatests/com/google/auth/http/HttpCredentialsAdapterTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenCheckingTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
- pom.xml
This adds missing license headers.
It also adds automatic header checks on `mvn verify` (as well as `mvn test`). `verify` will fail if some java files are missing the license header.
> Add missing license headers and automatic checkstyle checks

- oauth2_http/java/com/google/auth/oauth2/AppEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/javatests/com/google/auth/oauth2/AppEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
This PR does the following:
- Remove `OAuth2Utils.exceptionWithCause`, use exception costructor instead
- Add package-private `AppEngineCredentials` to `google-auth-library-oauth2-http` that uses reflection to access AE SDK
- Modify `DefaultCredentialsProvider` to instantiate the new `AppEngineCredentials` class
/cc @garrettjonesgoogle @anthmgoogle
> Modify DefaultCredentialsProvider to use reflection to access AE SDK

- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
This adds more detailed javadoc to:
- `DefaultCredentialsProvider.getDefaultCredentials()`
- `GoogleCredentials.getApplicationDefault(Transport)`
- `GoogleCredentials.getApplicationDefault(Transport)`
@lesv do you mind having a look at this?
> Add better javadoc for Application Default Credentials

- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
- appengine/javatests/com/google/auth/appengine/MockAppIdentityService.java
- credentials/java/com/google/auth/ServiceAccountSigner.java
- credentials/javatests/com/google/auth/SigningExceptionTest.java
- credentials/pom.xml
- oauth2_http/java/com/google/auth/oauth2/AppEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AppEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
This PR does the following:
- Add `ServiceAccountSigner` interface and related tests
- Add signing capabilities to `AppEngineCredentials` class in `appengine` package
- Add signing capabilities to service account and AE credentials in `oauth` package
> Add signing capabilities to AppEngine and service account classes

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
While integrating this library with `google-cloud-java` I realized there is no easy way to create `ServiceAccountCredentials` and `ServiceAccountJwtAccessCredentials` from a JSON credentials file.
It's important to have such methods for users that are willing to create an implementation of `ServiceAccountSigner`. The factory method `fromStream` in `GoogleCredentials` is not a good fit as it would require casting to get a `ServiceAccountCredentials` instance.
This should probably trigger a new release, I wish I had identified this earlier.
/cc @garrettjonesgoogle @anthmgoogle @lesv
> Add fromStream to ServiceAccountCredentials and ServiceAccountJwtAccessCredentials

- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
s/specifed/specified
And remove redundancy (should be used) in exception message.
> Fix a trivial typo and remove redundancy

- RELEASE.md
- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
1. Update versions to 0.7.0
2. Odd no one updated it to 0.7.0-SNAPSHOT earlier
> Prepare for Release

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
> Retry HTTP failures in ServiceAccountCredentials.refreshAccessToken

- README.md
- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Adapt fix from Apiary client libraries. Currently untested.
Addresses #109.
> Retry GCE environment check for Application Default Credentials

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
> Extracting the project_id field from service account JSON files

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
If the token server responds with a large `expires_in` value to the token refresh request, the `ServiceAccountCredential` class runs into an integer overflow. I've added more information at #120.
This patch fixes the issue, and provides a test case (test case fails without the fix). This is not a critical issue, as we can expect most token servers to be well behaved. But it would be nice if the credentials were able to handle the case where the server responds with a large `expires_in` value.
> Fixing an Integer Overflow Issue

- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
GAE java 8 standard environment supports Java native threads.  However `getDefaultCredentials()` call will fail on GAE J8 if it is called in a native thread (i.e. threads not managed by appengine runtime) due to the inaccessibility of native threads to appengine APIs. For GAE java8, same as compute engine, metadata serve should be used to construct `Credentials`.
> use metadata server to get credentials for GAE 8 standard environment

- oauth2_http/java/com/google/auth/oauth2/ClientId.java
- oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/http/HttpCredentialsAdapterTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ClientIdTest.java
- oauth2_http/javatests/com/google/auth/oauth2/CloudShellCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
- Add inner Builder class to each data container type classes
- Add `of` method of classes with single parameter constructor
- Update tests
TODO: Switch the rest of the auth lib to builder pattern
> Switch OAuth2 HTTP surface to use builder pattern

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Deserialization of ServiceAccoutnCredentials broke in 0.7.0 via this commit:
https://github.com/google/google-auth-library-java/commit/432ee7e507e3dfa730a5001a2e561cd65e0ba721#diff-e186a7a41155398a3502025e16ac1508L479
It removed the java deserialization hook readObject to properly deserialize the transient transportFactory field.
This PR reverts that change and adds a test
> Fix NPE deserializing ServiceAccountCredentials

- README.md
- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
The PR to bump the version to 0.8.0
(https://github.com/google/google-auth-library-java/pull/126)
was not merged before additional commits were merged, so it had to
be closed out. This PR bumps to the proper SNAPSHOT version for the
next release. Commit 0fab63c corresponds to the actual 0.8.0 release.
> Fixing version to 0.8.1-SNAPSHOT

- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
- oauth2_http/java/com/google/auth/oauth2/ClientId.java
- oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
- Removing Guava from surface
- Renaming of() methods to create() (using deprecation)
- Adding @deprecated javadoc to explain changes that callers need to make
- Migrating internal usage of deprecated methods that was missed previously
> Surface cleanup

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- pom.xml
Use guava's LoadingCache to cache JWT tokens. This should address performance for both clientside & serverside:
- Avoid the need for the client to recompute the signature
- Allows the serverside to cache tokens
Benchmarks (n1-standard-4):
- Generating a JWT token takes about 7~8ms (p50) on an idle machine
- Additionally, the newly generated tokens will add 9ms to p99 processing on serverside (for Cloud Bigtable)
- For reference, Cloud Bigtable has a 5ms response @ p99 using cached JWTs or OAuth tokens.
- Combined, the clientside & serverside overhead for using uncached JWT tokens triples Cloud Bigtable's p99 latency.
Merging this PR will have a significant impact on the consistency of Cloud Bigtable's performance (and other low latency products as well).
> Add caching for JWT tokens

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
This is important for testing (where we need to e.g. use the staging
Google OAuth server instead of prod) or IoT (where we need to use a
custom IoT token server instead of prod).
This commit is a copy of google-internal change cl/183885510.
Fixes #159.
> Read token_uri from service account JSON.

- README.md
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/javatests/com/google/auth/TestUtils.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
Adds instance method to explicitly refresh OAuth2Credentials if they need fetching or refreshing.
#143 
#147
> Add OAuth2Credentials#refreshIfExpired()

- README.md
- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
Changes:
* Read token_uri from service account JSON (#160)
* Add `OAuth2Credentials#refreshIfExpired()` (#163)
* Log warning if default credentials yeids a user token from gcloud sdk (#166)
* `ComputeEngineCredentials` implements `ServiceAccountSigner` (#141)
* Various documentation fixes
> Bump release to 0.10.0

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
Adding note about enabling the IAM API and requiring the
iam.serviceAccounts.signBlob permission.
Fixes #175
> Documentation for ComputeEngineCredential signing.

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
Currently in case of problems with token refresh is unclear what caused the problem and this change brings additional details.
Related to https://github.com/JetBrains/teamcity-google-storage/pull/9
> Show error message in case of problems with getting access token

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
Adding a note about the NO_GCE_CHECK environment variable to the 404 error when the metadata server is not contactable.
This makes the workaround to issue #204 much easier to discover.
> Add note about NO_GCE_CHECK to Metadata 404 Error

- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
Defining a new environment variable SUPPRESS_GCLOUD_CREDS_WARNING.
Setting this to true suppresses the end user credentials warning.
Fixes #193
> Option to suppress end user credentials warning.

- README.md
- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockIAMCredentialsServiceTransport.java
Addresses https://github.com/googleapis/google-auth-library-java/issues/210
Allow for `ImpersonatedCredentials` in core auth library set.  Instructions to repro or to run system tests:
```
```
output of unittests ran:
```
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.066 s - in com.google.auth.oauth2.ImpersonatedCredentialsTest
``
> Add ImpersonatedCredentials

- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
* Only use a single private constructor
* Caught and wrapped exceptions now provide better message and set the original error as the cause
* Various documentation fixes
> Cleanup ImpersonatedCredentials

- README.md
- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
11-14-2018 14:53 PST
- Show error message in case of problems with getting access token ([#206](https://github.com/google/google-auth-library-java/pull/206))
- Add note about `NO_GCE_CHECK` to metadata 404 error message ([#205](https://github.com/google/google-auth-library-java/pull/205))
- Add ImpersonatedCredentials ([#211](https://github.com/google/google-auth-library-java/pull/211))
- Add option to suppress end user credentials warning. ([#207](https://github.com/google/google-auth-library-java/pull/207))
- Update google-http-java-client dependency to 1.27.0 ([#208](https://github.com/google/google-auth-library-java/pull/208))
- README grammar fix ([#192](https://github.com/google/google-auth-library-java/pull/192))
- Add unstable …
> Release google-auth-library-java v0.12.0

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
@chingor13 Thanks for addressing this originally, I think this improves on what you did by fixing an issue with repeated log outputs.  It also makes the stack traces only output on `LogLevel.FINE` level since we have people regularly getting 3 repeated stack traces every time they run is alarming and not very helpful.  
* Moving the stacktrace to be FINE output since stacktraces are alarming.
* Making the INFO level log message occur only once instead of potentially many times.
Further improvements to #199 and #198
> Improve log output when detecting GCE

- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
> Overload GoogleCredentials.createScoped with variadic arguments

- README.md
- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
01-17-2019 12:40 PST
- Use OutputStream directly instead of PrintWriter ([#220](https://github.com/google/google-auth-library-java/pull/220))
- Improve log output when detecting GCE ([#214](https://github.com/google/google-auth-library-java/pull/214))
- Overload GoogleCredentials.createScoped with variadic arguments ([#218](https://github.com/google/google-auth-library-java/pull/218))
- Update google-http-client version, guava, and maven surefire plugin ([#221](https://github.com/google/google-auth-library-java/pull/221))
- Enable autorelease ([#222](https://github.com/google/google-auth-library-java/pull/222))
- Tests: Enable a test that was missing the test annotation ([#219](https://github.com/google/google-auth-library-java/pull/219)) …
> Release google-auth-library-java v0.13.0

- README.md
- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ClientId.java
- oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- pom.xml
Immediately following the last release is the best time to rip out all the deprecated methods.
> Remove deprecated methods

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Ref: https://github.com/googleapis/google-cloud-java/issues/4557
Update signBlob request to use new API endpoint which will help resolve issue referenced above.
API: https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts/signBlob
> Update Sign Blob API

- README.md
- pom.xml
This moves Guava and AppEngine API SDK forward. 
It resolves a minor inconsistency in the version definition for the AppEngine API SDK.
It also moves the google-http-java-client *backwards* to 1.27.0 because 1.28.0 made an incompatible change that breaks google-cloud-java (which depends on 1.27.0) and using 1.28.0 here risks runtime problems down the line.
> Update dependencies versions

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
> Fix#228 update default metadata url

- README.md
- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
03-25-2019 14:02 PDT
- update default metadata url ([#230](https://github.com/googleapis/google-auth-library-java/pull/230))
- Remove deprecated methods ([#190](https://github.com/googleapis/google-auth-library-java/pull/190))
- Update Sign Blob API ([#232](https://github.com/googleapis/google-auth-library-java/pull/232))
- Upgrade http client to 1.29.0. ([#235](https://github.com/googleapis/google-auth-library-java/pull/235))
- update deps ([#234](https://github.com/googleapis/google-auth-library-java/pull/234))
- Update README.md ([#233](https://github.com/googleapis/google-auth-library-java/pull/233))
- Bump next snapshot ([#225](https://github.com/googleapis/google-auth-library-java/pull/225))
- Provide STAGING_REPOSITORY_ID as an …
> Release v0.14.0

- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
Call `createScoped` implementation instead of endlessly recursing.
> createScoped: fix endless recursion

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
To be deleted at a later time.
> Add back in deprecated methods in ServiceAccountJwtAccessCredentials

- README.md
- appengine/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
03-27-2019 12:42 PDT
- createScoped: make overload call implementation ([#229](https://github.com/googleapis/google-auth-library-java/pull/229))
- Add back in deprecated methods in ServiceAccountJwtAccessCredentials ([#238](https://github.com/googleapis/google-auth-library-java/pull/238))
> Release google-auth-library-java v0.15.0

- .kokoro/release/publish_javadoc.cfg
- .kokoro/release/publish_javadoc.sh
- appengine/pom.xml
- pom.xml
- versions.txt
We now will use `gcp-docpublisher` to push built javadoc to our documentation staging area.
> Javadoc publish kokoro job uses docpublisher

- bom/README.md
- bom/pom.xml
- pom.xml
We should be publishing a BOM for dependency management.
This bom should be imported by google-cloud-java and the com.google.cloud:libraries-bom
> Add google-auth-library-bom artifact

- README.md
- appengine/pom.xml
- bom/README.md
- bom/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
06-04-2019 09:41 PDT
- Add google-auth-library-bom artifact ([#256](https://github.com/google/google-auth-library-java/pull/256))
- Update dependency com.google.http-client:google-http-client to v1.30.0 ([#261](https://github.com/google/google-auth-library-java/pull/261))
- Update dependency com.google.http-client:google-http-client to v1.29.2 ([#259](https://github.com/google/google-auth-library-java/pull/259))
- Update dependency org.sonatype.plugins:nexus-staging-maven-plugin to v1.6.8 ([#257](https://github.com/google/google-auth-library-java/pull/257))
- Update to latest app engine SDK version ([#258](https://github.com/google/google-auth-library-java/pull/258))
- Update dependency org.apache.maven.plugins:maven-source-plugin to …
> Release google-auth-library-java v0.16.0

- README.md
- appengine/pom.xml
- bom/README.md
- bom/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
06-06-2019 13:10 PDT
- Update dependency com.google.http-client:google-http-client to v1.30.1 ([#265](https://github.com/google/google-auth-library-java/pull/265))
- Add credentials for autorelease ([#267](https://github.com/google/google-auth-library-java/pull/267))
- Add developers section to google-auth-library-bom pom.xml
- Bump next snapshot ([#264](https://github.com/google/google-auth-library-java/pull/264))
> Release google-auth-library-java v0.16.1

- .kokoro/build.sh
- .kokoro/release/stage.sh
- pom.xml
After autorelease pushes to Sonatype, the release will automatically be promoted.
You can do the same behavior locally by setting `-Ddeploy.autorelease=true` when running `mvn deploy`
> Autorelease will also auto publish

- README.md
Adds an example using `HttpCredentialsAdapter`
Fixes https://github.com/googleapis/google-cloud-java/issues/3013
> README section for interop with google-http-client

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
> Adds metadata-flavor header to metadata server ping for compute engine

- README.md
- appengine/pom.xml
- bom/README.md
- bom/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
06-26-2019 06:39 PDT
- Add metadata-flavor header to metadata server ping for compute engine ([#283](https://github.com/google/google-auth-library-java/pull/283))
- Import http client bom for dependency management ([#268](https://github.com/google/google-auth-library-java/pull/268))
- README section for interop with google-http-client ([#275](https://github.com/google/google-auth-library-java/pull/275))
- Autorelease should actually autorelease
- Autorelease will also auto publish ([#271](https://github.com/google/google-auth-library-java/pull/271))
- Group AppEngine packages for renovate
- Bump next snapshot ([#270](https://github.com/google/google-auth-library-java/pull/270))
> Release google-auth-library-java v0.16.2

- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockIAMCredentialsServiceTransport.java
Fixes https://github.com/googleapis/google-cloud-java/issues/5043
Adds `Signer` capability to `ImpersonatedCredentials`.  This will allow impersonated credentials to make signedURLs and basically, just sign bytes as the `target_credential`
sample usage
```java
ServiceAccountCredentials sourceCredentials = ServiceAccountCredentials
.fromStream(new FileInputStream("svc_account.json"));
sourceCredentials = (ServiceAccountCredentials) sourceCredentials
.createScoped(Arrays.asList("https://www.googleapis.com/auth/iam"));
ImpersonatedCredentials targetCredentials = ImpersonatedCredentials.create(sourceCredentials,
"impersonated-account@project.iam.gserviceaccount.com", null,
Arrays.asList("https://www.googleapis.com/auth/devstorage.read_only"), 300);
Storage storage_service = …
```
> Add Signer for impersonatied credentials

- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
Currently, you can call `getApplicationDefault()` on a subclass of `GoogleCredentials` which will try to detect your execution environment. This does not make sense for the subclasses as you are not guaranteed to get back an instance of that class (especially for `com.google.auth.appengine.AppEngineCredentials` which will never be returned).
This PR marks `getApplicationDefault()` and `getApplicationDefault(HttpTransportFactory)` as deprecated to signal to users that they should not be using this method. It does turn around and call `GoogleCredentials.getApplicationDefault()` to preserve the current behavior, but it also logs a warning.
This should help alleviate some confusion around `com.google.auth.appengine.AppEngineCredentials` like in #272
> Log warnings and deprecate AppEngineCredentials.getApplicationDefault

- appengine/pom.xml
This direct dependency was added in #288, but the presubmit check was not yet set up. It was already being transitively pulled in via `google-auth-library-oauth2-http`
> Fix declared dependencies from merge issue

- .kokoro/continuous/propose_release.cfg
- .kokoro/continuous/propose_release.sh
- .kokoro/release/bump_snapshot.cfg
- .kokoro/release/bump_snapshot.sh
Commits to master will propose a release.
After releases are published, it will trigger a job to bump the snapshot.
> chore: add kokoro configs for proposing releases automatically

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockIAMCredentialsServiceTransport.java
> fix some unused code and deprecation warnings

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IamUtils.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
Least invasive change that partially addresses #314 but  we need to change the API to correctly fix this. @chingor13
> throw SigningException as documented

- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
@chingor13 
per go/java-practices "We discourage the general practice of marking all parameters or local variables as final1. There are occasional special circumstances where final is useful, such as the use of a blank final."
> remove final on local variables

- .kokoro/continuous/propose_release.sh
Reverts googleapis/google-auth-library-java#319
> revert: "build: run in debug mode"

- oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
- oauth2_http/java/com/google/auth/oauth2/JwtCredentials.java
- oauth2_http/java/com/google/auth/oauth2/JwtProvider.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- oauth2_http/pom.xml
- pom.xml
- renovate.json
Adds the ability to create custom JWT Credentials (`JwtCredentials`) with custom claims from a `ServiceAccountJwtAccessCredentials` instance.
* `ServiceAccountJwtAccessCredentials` will continue to provide on-demand credentials where the audience is based on the requested URI
* Adds `JwtCredentials` class which can be directly built with a `PrivateKey`, privateKeyId string, and custom `JwtCredentials.Claims`. You can also build new `JwtCredentials` via `JwtCredentials#jwtWithClaims(JwtCredentials.Claims)` which only overrides the new specified claims fields.
* Add `ServiceAccountJwtAccessCredentials#jwtWithClaims(JwtCredentials.Claims)` which will provide a `JwtCredentials` instance with custom claims
* Changed the credentials cache to be keyed of the full Claims object rather than just …
> feat: adds JwtCredentials with custom claims

- appengine/pom.xml
- bom/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
2/3 for #324 
As stated in #325 by @elharo , Automatic-Module-Name need to be in submodules and not in parent.
lmk if everything is okay.
> feat: add Automatic-Module-Name to manifest (#324)

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IamUtils.java
- oauth2_http/java/com/google/auth/oauth2/IdToken.java
- oauth2_http/java/com/google/auth/oauth2/IdTokenCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdTokenProvider.java
- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/IdTokenCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/IdTokenTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockIAMCredentialsServiceTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Fixes https://github.com/googleapis/google-auth-library-java/issues/99
Adds support for IDTokens into `google-auth-java` for `ServiceAccountCredentials`, `ComuteEngineCredentials` and `ImpersonatedCredentials` 
GCP users currently have to do these steps manually and outside of `google-auth-java`:   
ref: https://github.com/salrashid123/salrashid123.github.io/tree/master/google_id_token#java
this change wraps the various flows into the library
I do not have any testcases here. I'm submitting this first for review of the api surface.  Usage for this change is shown here:
https://github.com/googleapis/google-auth-library-java/issues/99#issuecomment-512899563
> feat: add IDTokenCredential support

- bom/README.md
This fixes the incorrect artifactId for the pom.xml example.
> docs: fix minor typo in google-auth-library-bom README

- oauth2_http/java/com/google/auth/oauth2/IdToken.java
I think we should hide `getJsonWebSignature()` for now until we know if we actually want to expose this class or a version from a different, better supported JWT library.
> chore: hide `IdToken#getJsonWebSignature()`

- oauth2_http/java/com/google/auth/oauth2/JwtCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
Fixes #335
This was a regression from 0.16.2
Note that if you load Service Account Credentials from json, that field is required.
> fix: allow unset/null privateKeyId for JwtCredentials

- bom/pom.xml
The google-auth-library-appengine dependency is incorrectly named in the BOM.
> fix: typo in BOM dependency

- oauth2_http/pom.xml
- pom.xml
Fixes #357 
@BenWhitehead @netdpb @chingor13
> move autovalue into annotation processor path instead of classpath

- versions.txt
We had an inadvertent tag for 0.17.3 which caused release-please to try and release the wrong version. Pushing this to master should retrigger and fix the release versioning.
> build: fix version and tags for release-please

- CHANGELOG.md
- README.md
- appengine/pom.xml
- bom/pom.xml
- credentials/pom.xml
- oauth2_http/pom.xml
- pom.xml
- versions.txt
We should actually release this as 0.18.0 rather than 0.17.3
See #361
> chore: release 0.18.0

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
The explicit IP address is no longer used.
> Remove outdated comment on explicit IP address

- README.md
@chingor13 It does not appear necessary to manually install the artifacts when using Maven.
> docs: Remove unnecessary steps

- oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
Made JwtClaims#Builder methods public so that the user could create JwtClaims instance.
towards #349
> chore: updated `JwtClaims.Builder` methods to `public`

- README.md
Showing an example of obtaining default credentials with configuring a proxy with authentication.
> chore: add docs on configuring a proxy

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
Fixes #430
Also changing the INFO message that we couldn't detect compute engine credentials as that's a perfectly normal case and can be checked by the return value.
> feat: add logging at FINE level for each step of ADC

- oauth2_http/java/com/google/auth/oauth2/TokenVerifier.java
- oauth2_http/javatests/com/google/auth/oauth2/TokenVerifierTest.java
Adjust the license from Apache to BSD 3, the one used by the project.
Fixes #260
> chore: fix license on token verifier classes

- oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
We need to support generic formats for `IdentityPoolCredentials` (text/json). The environments we support use both formats - K8s (file-sourced) returns the token as text, and Azure (url-sourced) returns the token in JSON format. 
The credential source now supports a `format` entry:
```
"credential_source": {
"format": {
"type": "json",
"subject_token_field_name": "subject_token"
}
}
```
If no format is provided, we default to text.
> feat: support generic token formats in IdentityPoolCredentials

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
Adds a AwsCredentials class that supports retrieving AWS credentials from both environment variables and the security-credentials endpoint. It handles generating the GetCallerIdentity signed request (delegated to AwsRequestSigner) and building the subject token to be passed to GCP STS.
> feat: adds support for AWS credentials

- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
This PR does the following:
- Adds quota project ID to requestMetadata when present
- Removes use of Truth & adds missing tests for AwsCredentials in ExternalAccountCredentialsTest
> feat: add quota project ID to requestMetadata if present

- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
Cloud IAM now supports extended 12h lifespan for access token:
https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#sa-credentials-oauth
A separate PR should be made to allow developers to specify the desired lifespan of the granted token.
> fix: remove 1 hour limit for the impersonated token

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
When the service_account_impersonation_url is provided, we must exchange the external account GCP access token for a service account impersonated token.
This PR removes the duplicated code in ExternalAccountCredentials that makes the IAM generateAccessToken call and delegates it to ImpersonatedCredentials.
> chore: use ImpersonatedCredentials for service account impersonation for 3pi

- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Refactors the injection of the quota project id (and possibly other future headers) into the entrypoint that caches the request metadata (in OAuth2Credentials).
Fixes #507
> fix: quotaProjectId should be applied for cached `getRequestMetadata(URI, Executor, RequestMetadataCallback)`

- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
@arithemtic1728 mostly Javadoc
> fix: style nits

- oauth2_http/java/com/google/auth/oauth2/JwtProvider.java
> fix typos in Javadoc

- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
> fix: replace non-precondition use of Preconditions

- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
- appengine/pom.xml
This library is pre-1.0. If any dependencies need this, we should find out now so we can undeprecate these methods.
> fix: remove deprecated methods

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdToken.java
- oauth2_http/java/com/google/auth/oauth2/IdTokenCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdTokenProvider.java
- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/java/com/google/auth/oauth2/JwtProvider.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/TokenVerifier.java
These features have been available for months and have not received bug reports.
> feat: promote IdToken and JWT features

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Fixes: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/4907#issuecomment-802096084
> fix: fix service account credentials createScopedRequired

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
AWS_DEFAULT_REGION env var should be checked after AWS_REGION. See b/182491887.
> fix: support AWS_DEFAULT_REGION env var

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Address https://github.com/googleapis/google-auth-library-java/pull/601#discussion_r597240454
> fix: follow up fix service account credentials createScopedRequired

- .kokoro/nightly/integration.cfg
- .kokoro/presubmit/integration.cfg
Fixes #618 ☕️
GCS_BUCKET env needed [here](https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java#L204) but set up got removed with synthtool update [here](https://github.com/googleapis/google-auth-library-java/commit/a5150b5b677cbb7e5f03e3ba9b43c5d7b030015e#diff-eb8df92b5a330fd9043fb3f02dd7c8f35196ac8484cd0ea1798f95ecbe395f92L39)
> chore: add GCS_BUCKET env var

- synth.py
Add integration.cfg files to excludes list in synth.py to prevent synthtool from removing the GCS_BUCKET environment variable.
> chore: add integration.cfg to excludes list in synth.py

- pom.xml
> deps: update guava patch

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
`getUriForSelfSignedJWT(URI uri)` is used to convert `"https://compute.googleapis.com/compute/v1/projects/"` to `"https://compute.googleapis.com/"`, so if the uri's scheme or host is null (for instance when user provided an uri like `compute.googleapis.com`), it should return the original uri.
> fix: use orginal url as audience for self signed jwt if scheme or host is null

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Adding additional data to debug issues, where token request intermittently returns invalid_grant errors. 
This does not fix the #654 completely, but a step forward. 
Fixes #654 ☕️
> feat: Returning an issuer claim on request errors

- oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
- oauth2_http/javatests/com/google/auth/oauth2/CredentialAccessBoundaryTest.java
- oauth2_http/pom.xml
Adds CAB rule classes (see go/cab-client)
> feat: adds CAB rules classes

- oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/JwtClaimsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
This PR allows self signed jwt to use scopes. 
AIP: https://google.aip.dev/auth/4111
googlers see: go/yoshi-self-signed-jwt-phase-2
In ServiceAccountCredentials, this PR now uses JwtCredentials instead of ServiceAccountJwtCredentials. As a result, this PR reverted the changes made to ServiceAccountJwtCredentials in #572 #642 so the ServiceAccountJwtCredentials is the same as what it was before phrase 1. 
The current behavior for ServiceAccountCredentials is:
```
if (hasScopes):
if (useJwtAccessWithScope):
// create a self signed JWT with "scope" set to the scope
else:
// call oauth token endpoint
else:
// create a self signed JWT with modified uri as the audience
``` 
Follow up PRs:
(1) gax-java: https://github.com/googleapis/gax-java/pull/1420
(2) gapic-generator-java: it will be a very …
> feat: allow scopes for self signed jwt

- CHANGELOG.md
- README.md
- appengine/pom.xml
- bom/pom.xml
- credentials/pom.xml
- oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ITDownscopingTest.java
- oauth2_http/javatests/com/google/auth/oauth2/JwtClaimsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/functional/FTServiceAccountCredentialsTest.java
- oauth2_http/pom.xml
- pom.xml
- scripts/downscoping-with-cab-setup.sh
- versions.txt
- Provides a setup script (downscoping-with-cab-setup.sh) to make configuration changes on the current project, if needed. The setup script only needs to be run once on a project (already ran).
- See go/cab-client-integration-testing for more information.
> test: adds integration tests for downscoping with credential access boundaries

- .github/sync-repo-settings.yaml
- .github/workflows/ci.yaml
- .repo-metadata.json
- pom.xml
Release-As: 1.0.0
feat!: updating google-auth-library-java min Java version to 1.8
> feat: GA release of google-auth-library-java (ver 1.0.0)

- oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
- oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2CredentialsWithRefresh.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
- oauth2_http/java/com/google/auth/oauth2/StsRequestHandler.java
- oauth2_http/java/com/google/auth/oauth2/StsTokenExchangeResponse.java
- oauth2_http/javatests/com/google/auth/oauth2/CredentialAccessBoundaryTest.java
- oauth2_http/javatests/com/google/auth/oauth2/DownscopedCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ITDownscopingTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsWithRefreshTest.java
- oauth2_http/javatests/com/google/auth/oauth2/StsRequestHandlerTest.java
- scripts/downscoping-with-cab-setup.sh
See go/cab-client. This feature is publicly documented [here](https://cloud.google.com/iam/docs/downscoping-short-lived-credentials). 
Summary:
- Adds a new DownscopedCredentials class that enables the ability to downscope, or restrict, the IAM permissions that a short-lived credential can use for Cloud Storage. This is done by defining a CredentialAccessBoundary which specifies the upper bound of permissions the downscoped credential will be able to access. 
- OAuth2CredentialsWithRefresh enables access token refresh via a developer defined refresh handler.
- With CAB, STS may not always return an expires_in. The STS utility has been updated to reflect this. When not returned, the expires_in is copied from the source credential, when available.
- Includes integration tests with a one …
> feat: downscoping with credential access boundaries

- README.md
- oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/DownscopedCredentialsTest.java
Documentation for downscoping with credential access boundaries. 
Samples will be added in a separate PR.
> docs: updates README for downscoping with CAB

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockRequestMetadataCallback.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
ComputeEngine metadata server has its own token caching mechanism that will return a cached token
until the last 5 minutes of its expiration. This has a negative interaction with stale token refreshes because 
stale token refresh kicks in T-6mins until T-5mins. This will cause every stale refresh to return the same 
stale token.
This PR updates the timing for ComputeEngineCredentials to start a stale refresh at T-4mins and consider 
the token expired at T-3 mins. The implementation is a bit noisy because it includes a change OAuth2Credentials 
to make the thresholds configureable and now that we targeting java8, I migrated to using java8 time data types.
> fix: timing of stale token refreshes on ComputeEngine

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/TokenVerifierTest.java
The self-signed JWT is not supported with domain delegation. Therefore disabling the self-signed JWT in that case.
> fix: disabling self-signed jwt for domain wide delegation

- appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
- appengine/pom.xml
- pom.xml
It belongs to #756  . It's the first iteration. That's why I don't use `fixed` notation for the issue.
> Migration tests in appengine module from JUnit4 to JUnit5 (#756)

- README.md
- pom.xml
The `compile` configuration doesn't work in recent Gradle versions.
> chore: update README to migrate deprecated usage

- oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
> fix: remove erroneous check for the subject token field name for text credential source

- .gitignore
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
After this change, service account can send requests to the private endpoint (if configured) and still use the oauth2.googleapis.com/token in the assertion.
Fixes #809 ☕️
> feat: setting the audience to always point to google token endpoint

- pom.xml
The release failed again https://github.com/googleapis/google-auth-library-java/pull/866. Reverting recent version upgrade of the nexus staging plugin.
----
> fix(ci): downgrading nexus staging plugin 1.6.8

- README.md
- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
> feat: Add AWS Session Token to Metadata Requests

- README.md
> docs: update wif documentation with enable-imdsv2 flag

- README.md
- oauth2_http/java/com/google/auth/oauth2/ExecutableResponse.java
- oauth2_http/java/com/google/auth/oauth2/PluggableAuthCredentials.java
- oauth2_http/java/com/google/auth/oauth2/PluggableAuthHandler.java
- oauth2_http/javatests/com/google/auth/oauth2/ExecutableResponseTest.java
- oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthHandlerTest.java
For successful responses, the `expiration_time` field is only required
when an output file is specified in the credential configuration.
> fix: updates executable response spec for executable-sourced credentials

- oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
https://oauth2.googleapis.com/revoke does not have a GET endpoint. It has only a POST. So updating the code accordingly.
Fixes #<782> ☕️
> fix: change revoke request from get to post

- oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/TokenVerifierTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Setting retry count to default temporarily to remove direct dependency on the latest version of HttpClient. 
Enabling IOExcpetions retries and marking as retryable to match original behavior.
> Fix: setting the retry count to default value and enabling ioexceptions to retry

- README.md
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java
- oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthCredentialsTest.java
Adds support for configurable token lifespan via the service_account_impersonation object in the ADC. Also adds unit + integration tests.
See go/byoid-sdk-service-account-impersonation-ctl
> feat: adds configurable token lifetime support

- samples/snippets/src/main/java/AuthenticateImplicitWithAdc.java
- samples/snippets/src/main/java/IdTokenFromImpersonatedCredentials.java
- samples/snippets/src/main/java/IdTokenFromMetadataServer.java
- samples/snippets/src/main/java/IdTokenFromServiceAccount.java
- samples/snippets/src/main/java/VerifyGoogleIdToken.java
- samples/snippets/src/test/java/SnippetsIT.java
Changes:
1. Modified Auth implicit sample to use GCS instead of GCE.
2. Modified comments
3. Minor variable value refactoring
> docs(samples): modified comments in the samples and minor refactor

- renovate.json
The synthtool PR (https://github.com/googleapis/google-auth-library-java/pull/1004) didn't include these changes for some reason so this PR manually brings them in.
> chore: exclude requirements.txt file from renovate bot

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
Updating AWS credential source validation as per new updates in [AIP](https://github.com/aip-dev/google.aip.dev/pull/959). Make sure the host of url, region_url and imdsv2 session token url belong to AWS metadata server.
> fix: Validate url domain for aws metadata urls

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
Validate aws metadata urls only if they are not null or empty. It is possible to fetch tokens successfully even if metadata urls are not provided but required environment variables are set. If both metadata urls and env vars are not provided, we will throw an exception.
> fix: empty string check for aws url validation

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
Fixes an issue introduced by the AWS IMDSv2 changes where the metadata server is being called even if everything is retrievable through the defined environment variables.
> fix: AwsCredentials should not call metadata server if security creds and region are retrievable through environment vars

- oauth2_http/javatests/com/google/auth/oauth2/AwsRequestSignerTest.java
Enforce Locale.US for AwsRequestSignerTest. Date parsing can fail in other locales.
Specifically, in `en-CA` (Canada), the tests's defined date `Mon, 09 Sep 2011 23:36:00 GMT` won't parse correctly, as the weekday short name for the locale is `Mon.` (extra period).
Fixes #1110  ☕️
> fix: Enforce Locale.US for AwsRequestSignerTest

- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2CredentialsWithRefresh.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsWithRefreshTest.java
> fix: ensure both refreshMargin and expirationMargin are set when using OAuth2CredentialsWithRefresh

- oauth2_http/java/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuthException.java
- oauth2_http/java/com/google/auth/oauth2/StsRequestHandler.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/OAuthExceptionTest.java
Adds support for external account authorized user credentials. 
See go/gcloud-3pi-headful.
> feat: adds external account authorized user credentials

- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
Listeners for Futures should generally use Futures.addCallback() or Futures.getDone() when called. This makes it clear they won't block and allows tooling to know it will never block.
cl/492555987
> oauth2_http: Use Futures.getDone() instead of Future.get() in listener

- README.md
"google-auth-library" was ambiguous.
> docs: clarified Maven artifact for HTTP-based clients

- oauth2_http/java/com/google/auth/oauth2/DefaultPKCEProvider.java
- oauth2_http/java/com/google/auth/oauth2/PKCEProvider.java
- oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultPKCEProviderTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
go/client-auth-java-oauth-pkce
> feat: Add PKCE to 3LO exchange.

- README.md
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Removed pattern checking for external accounts to support TPC urls. Also added readme change to explain risk to users.
> fix: Removed url pattern validation for google urls in external account credential configurations

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
GAPIC clients all use self signed jwt (with scopes) now. Currently we are creating a new jwt credential each time, and this causes perf issue, similar to https://github.com/googleapis/google-cloud-java/issues/3149.
In this PR we create one jwt cred and reuse it each time.
Internal bug:  b/268603529
> fix: create and reuse self signed jwt creds for better performance

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/java/com/google/auth/oauth2/SystemEnvironmentProvider.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthCredentialsTest.java
> fix: Make supporting classes of AwsCredentials serializable

- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
* fix: create and reuse self signed jwt creds for better performance
* only create jwt cred when needed
> fix: create and reuse self signed jwt creds for better performance 

- .kokoro/presubmit/graalvm-native-17.cfg
- .kokoro/presubmit/graalvm-native.cfg
This PR upgrades the Kokoro to run on the latest GraalVM version. The presubmit jobs are currently running in 22.2.0:
Stacktrace from [example PR:](https://github.com/googleapis/google-auth-library-java/pull/1189)
```
[1/7] Initializing...                                                                                    (7.9s @ 0.14GB)
Version info: 'GraalVM 22.2.0 Java 11 CE'
Java version info: '11.0.16+8-jvmci-22.2-b06'
C compiler: gcc (redhat, x86_64, 4.8.5)
Garbage collector: Serial GC
2 user-specific feature(s)
- com.oracle.svm.thirdparty.gson.GsonFeature
- org.graalvm.junit.platform.JUnitPlatformFeature
[junit-platform-native] Running in 'test listener' mode using files matching pattern [junit-platform-unique-ids*] found in folder …
```
> chore: update Kokoro job to GraalVM 22.3.2

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
See local doc for more info: [go/mds-auth-503](http://goto.google.com/mds-auth-503)
plus removing some temporary default values
> fix: marking 503 as retryable for Compute credentials

- oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
- oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
Sometimes customers might want to pass custom query parameters to the auth endpoint. Adding a property bag like solution so that customers can pass any key, value pair to the auth service.
> feat: Introduce a way to pass additional parameters to auhtorization url

- README.md
I recently switched to this library for a project, and since I just copied the info from the readme I used an ancient version at first. That was especially annoying since many APIs that would've been helpful for me during migration didn't exist back in version 1.3.0 (like creating ServiceAccountCredentials from a PKCS8 string without having to pass JSON).
I'd love to prevent other users from making the same mistake as myself in the future through this README update.
> chore: Update library definitions in README to the latest version

- .kokoro/build.sh
- oauth2_http/pom.xml
- owlbot.py
- pom.xml
Notable Changes:
- Removed surefire-junit47 provider which was conflicting with the native-maven-plugin's testing support. See https://github.com/googleapis/google-auth-library-java/pull/1329#discussion_r1388205323 for details. 
- Removed `fmt-maven-plugin ` to rely on the one defined in java-shared-config.
- Removed native profile to rely on the one defined in java-shared-config
- Removed `autovalue-java8` profile and the autovalue dependency declaration to use the one defined in java-shared-config. 
- Added `native-test` profile to explicitly include ITs and functional tests for native image compilation.
> chore: add java-shared-config as parent for consolidated version management

- README.md
The AIPs are not a good experience for customers, they are more of an internal resource, at least for auth. The Cloud authentication documentation includes a section about Application Default Credentials now, so that's a better place to send users.
> docs: Update README.md to link to Cloud authentication documentation rather than AIPs

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
- oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
This adds universe domain support to GCE credentials.
In case explicit universe_domain was provided - it takes priority
Otherwise - GCE credential tries to obtain a universe domain from Metadata service
If request fails with 404 or request returns an empty string - universe domain is set to GDU
If any other error - throws a retryable exception
> feat: adds universe domain support for compute credentials

- appengine/java/com/google/auth/appengine/AppEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
- oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GdchCredentials.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdTokenCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
- oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2CredentialsWithRefresh.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
- oauth2_http/pom.xml
[ErrorProne](https://errorprone.info/) flags several issues in the codebase, this pull request fixes some of them:
- Missing `@Override` annotations where needed
- Using of deprecated or incompatibel APIs for Base64 encoding
There's also a warning by maven due to conflicting / duplicate dependencies in pom.xml, this is also fixed.
> fix: handle error-prone warnings

- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Fixes #1347: ExternalAccountCredentials serialization is broken
> fix: Issue #1347: ExternalAccountCredentials serialization is broken

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/java/com/google/auth/oauth2/AwsSecurityCredentialsSupplier.java
- oauth2_http/java/com/google/auth/oauth2/ExternalAccountSupplierContext.java
- oauth2_http/java/com/google/auth/oauth2/FileIdentityPoolSubjectTokenSupplier.java
- oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
- oauth2_http/java/com/google/auth/oauth2/IdentityPoolSubjectTokenSupplier.java
- oauth2_http/java/com/google/auth/oauth2/InternalAwsSecurityCredentialsSupplier.java
- oauth2_http/java/com/google/auth/oauth2/UrlIdentityPoolSubjectTokenSupplier.java
- oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountSupplierContextTest.java
- oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java
- oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
Adds context object to pass from credentials to user defined suppliers.
> feat: Add context object to pass to supplier functions

- oauth2_http/java/com/google/auth/oauth2/ExternalAccountSupplierContext.java
Adds missing copyright header on external account supplier context class.
> fix: add missing copyright header

- README.md
Updates readme for supplier based external account credentials.
> docs: adds docs for supplier based external account credentials

- oauth2_http/java/com/google/auth/oauth2/DefaultPKCEProvider.java
- oauth2_http/javatests/com/google/auth/oauth2/DefaultPKCEProviderTest.java
Fixes
https://github.com/googleapis/google-auth-library-java/issues/1373.
> fix: Remove Base64 padding in DefaultPKCEProvider

- pom.xml
google-auth-library should inherit the DocFX profile from java-shared-config: https://github.com/googleapis/java-shared-config/blob/main/java-shared-config/pom.xml#L570
Removing this profile as it's causing issues with javadoc generation
> chore: remove DocFX profile

- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Makes the default sts token url logic in external account credentials universe aware.
> fix: makes default token url universe aware

- oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
- oauth2_http/java/com/google/auth/oauth2/AwsSecurityCredentialsSupplier.java
- oauth2_http/java/com/google/auth/oauth2/FileIdentityPoolSubjectTokenSupplier.java
- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
- oauth2_http/java/com/google/auth/oauth2/InternalAwsSecurityCredentialsSupplier.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/UrlIdentityPoolSubjectTokenSupplier.java
> chore: fix CI errors on javadoc

- oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
- oauth2_http/java/com/google/auth/oauth2/IamUtils.java
- oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
- oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
- oauth2_http/java/com/google/auth/oauth2/TokenVerifier.java
- oauth2_http/javatests/com/google/auth/oauth2/IamUtilsTest.java
Fixes https://github.com/googleapis/google-auth-library-java/issues/1451
The overall changes will be split into two parts. This part is part 1 where retries will be enabled and tests to cover successful and failed calls.
Part 2 will add additional tests to cover retries for the IAM Mock Server. Split it out to a separate PR since the IAM Mock Server will need to be refactored to support retries and variable number of responses. The refactor will touch multiple files that are non-related to adding retries to the Sign Blob RPC.
Changes:
1. Sign Blob RPC will have retries for certain 5xx status codes
2. Centralize default retry parameter values in Oauth2Utils for all retryable RPCs
> fix: Retry sign blob call  with exponential backoff

- renovate.json
This will avoid prs for deps major version updates be created by renovate bot. e.g. [hamcrest-core 1.3 -> 3.0](https://github.com/googleapis/google-auth-library-java/pull/1454)
This rule aligns with what sdk-platform-java's config [here](https://github.com/googleapis/sdk-platform-java/blob/9972e4791eba8e25955177693100815d1e99f66f/renovate.json#L88C20-L97C7)
> chore: disable major version updates in renovate config

- oauth2_http/javatests/com/google/auth/oauth2/ExecutableResponseTest.java
- oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthHandlerTest.java
Improve test error message to show expected and actual values on failure.
Example of unhelpful assertion message when using `assertTrue`: https://fusion2.corp.google.com/ci/kokoro/prod:cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-auth-library-java%2Fnightly%2Fintegration/activity/210e3a70-92c9-4601-8bcb-49e2a9bf5753/log
```
[ERROR] com.google.auth.oauth2.PluggableAuthHandlerTest.getExecutableResponse_oidcResponse -- Time elapsed: 0.011 s <<< FAILURE!
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.google.auth.oauth2.PluggableAuthHandlerTest.getExecutableResponse_oidcResponse(PluggableAuthHandlerTest.java:744)
```
> chore: use assertEquals to improve test error message

- credentials/java/com/google/auth/CredentialTypeForMetrics.java
- oauth2_http/java/com/google/auth/oauth2/IdTokenProvider.java
- oauth2_http/java/com/google/auth/oauth2/MetricsUtils.java
See go/bugpattern/ImmutableEnumChecker
Fixes #1525 ☕️
> fix: make some enum fields final

- oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
> fix: switch to universe-domain endpoint for ComputeEngineCredentials

- .kokoro/build.sh
- .kokoro/populate-secrets.sh
- .kokoro/presubmit/common.cfg
- .kokoro/presubmit/graalvm-native-a.cfg
- .kokoro/presubmit/graalvm-native-b.cfg
- oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java
- renovate.json
Notable Changes:
- Removed unused keystore settings.
- Replaced use of TRAMPOLINE_IMAGE environment variable with container_properties { docker_image ...}}
- Modified renovate bot settings to edit new docker_image property's value when a new version of java-shared-config is available.
> chore: migrate graalvm jobs to kokoro instance pool

- oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
- oauth2_http/java/com/google/auth/oauth2/SecureSessionAgent.java
- oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Autoconfig endpoint returns
```
{
s2a:
{
plaintext_address: ""
mtls_address: "" 
}
}
```
not 
```
{
plaintext_address: ""
mtls_address: "" 
}
```
> fix: JSON parsing of S2A addresses.

- oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
Fixes https://github.com/googleapis/google-auth-library-java/issues/1584
> chore: Remove outdated TODO comment in GoogleAuthException 

- .github/workflows/sonar.yaml
Context:
PRs from Forks do not have access to secrets which will cause the Sonar CI job to consistently fail. Disable the Sonar CI workflow from Forks.
> ci: Disable Sonar if PR comes from a fork

- cab-token-generator/java/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactory.java
- cab-token-generator/javatests/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactoryTest.java
- cab-token-generator/pom.xml
- oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
- pom.xml
Implement Client-Side CAB token generation.
* Temporarily added the staging repository for CEL with protobuf 3.25
* Add a new dependency tink for encryption.
* Will wait #1583 to be merged first and resolve conflicts
---
> feat: Implement Client-Side CAB token generation. 

- .github/workflows/members.json
The multi-approvers check will not require and additional human for these bot PRs.
> chore: add renovate-bot and release-please to members

- .github/workflows/multi_approvers.yaml
Download members.json so that the check works on other repos. Otherwise the following failure occurs:
https://github.com/googleapis/java-spanner/actions/runs/12993106224/job/36234542669
> chore: add step to download members.json

- oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
> fix: respect token_uri from json in UserCredentials creation.

- .github/workflows/members.json
`devoncarew` is a Googler who is contributing to Rust SDK.
> chore: add devoncarew to members.json

- README.md
This commit updates the README file to include instructions for setting up and using the client-side CAB feature.
Design doc: [go/client-side-cab-client-library-java](http://goto.google.com/client-side-cab-client-library-java)
> docs: Update README with client-side CAB instructions

- bom/pom.xml
We missed this as part of the CAB Token Generator PR  CC: @nbayati
> fix: Add cab-token-generator module to Auth BOM

- oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
- oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
- samples/snippets/pom.xml
I believe the issue that was reported in https://github.com/googleapis/google-auth-library-java/issues/1027 was actually resolved in https://github.com/googleapis/google-auth-library-java/pull/1636.
This PR is to add more tests to ensure that receiving non-2xx status codes back from the `idTokenWithAudience` are correctly caught.
Fixes https://github.com/googleapis/google-auth-library-java/issues/1027
> chore: Add test for non-2xx responses from idTokenWithAudience calls

- .github/release-please.yml
- .github/sync-repo-settings.yaml
This reverts commit fe4381513db1340190c4309a53c6265718682dde.
kokoro is only configured to run presubmit checks on branches end in .x
> Revert "feat: next release from main branch is 1.34.0 (#1698)"

- oauth2_http/java/com/google/auth/mtls/CertificateSourceUnavailableException.java
- oauth2_http/java/com/google/auth/mtls/WorkloadCertificateConfiguration.java
- oauth2_http/java/com/google/auth/mtls/X509Provider.java
- oauth2_http/javatests/com/google/auth/mtls/WorkloadCertificateConfigurationTest.java
- oauth2_http/javatests/com/google/auth/mtls/X509ProviderTest.java
This commit introduces the foundational components for workload identity mTLS authentication. It includes classes to load the certificate and private key file paths from a JSON configuration and to provide these credentials as a KeyStore.
This lays the groundwork for future implementation of trust chain handling and subject token generation.
> feat: Implement X509 certificate provider

- cab-token-generator/java/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactory.java
- cab-token-generator/javatests/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactoryTest.java
There are early adopters reporting that the padding at the end of the Client-Side CAB tokens can break some use cases including using URL-encoded token in URL. While we have other solutions to resolve this issue, we think it's better to remove the padding in the client library to stay consistent with other types of tokens.
> fix: Do not add padding in Client-Side CAB tokens.

- .github/workflows/multi_approvers.yaml
This is the last version that will support members.json.
> chore: pin version of multi-approvers workflow

- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
- oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
This PR handles correctly JSON null values for optional fields in ExternalAccountCredentials configuration.
This is likely a partial fix, other credential classes have the same issue (just search for `(String) json.get(` in the codebase).
The approach might applied to all json fields, including required ones, to avoid ClassCastException and have better errors.
Fixes #1705 ☕️
> fix: Handle optional fields with null JSON value in ExternalAccountCredentials gracefully

- .github/workflows/ci.yaml
this is order to support latest graalvm update
> chore: add jdk 24 to test matrixes

- oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
- oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
Fixes: https://github.com/googleapis/google-auth-library-java/issues/1443
For Googlers, see yaqs/7220478565953830912
> fix: update approval_prompt=force to prompt=consent

- oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
The Javadoc for ExternalAccountCredentials.java incorrectly referred to `GoogleCredential.Builder`. This commit corrects the reference to `GoogleCredentials.Builder`.
> docs: Update Javadoc reference in ExternalAccountCredentials

- oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
Follows up on recent changes of https://github.com/googleapis/google-auth-library-java/pull/1798 by adding additional instructions on generic `fromStream()` methods and explaining the security risk of using these.
> docs: additional information for deprecated fromStream() methods.
